Tree from XML should not have duplicate nodes
alliedtelesis/apteryx-netconf pull request #90
Opened 2024-10-21 22:21 UTC by tony-vanderpeet

When adding subtress to a GNode tree ensure that if the root of the tree being added is already a sub-node of the node to which the subtree is to be added, that we add the subtree under the existing node (removing the top of the subtree to do so).

This is not something that can be explicitly tested, but add some tests to at least ensure that the new code doesn't cause any problems.

2024-10-22 22:41 UTC, carlgsmith requested changes

2024-10-22 22:41 UTC, carlgsmith commented on tests/test_edit_config.py
> +def _get_subtree_as_json(f_value, wd=None):
_get_subtree_as_dict would be a more accurate naming

2024-10-22 22:41 UTC, carlgsmith commented on data.c
> +                        sub_cn = cn->children;
I think this might be unsafe for multiple children .. it will only update the parent link pointers for the first child ... so the second child will have a parent pointing to cn ... i think you have to (safely) loop through the children and (pre)pend them all to sub_node

2024-10-23 00:23 UTC, tony-vanderpeet commented on data.c
> +                        sub_cn = cn->children;
I am trying to think of a test case that would show this behaviour. And I can't offhand. I tried adding multiple users as in:
  <test>
    <settings>
      <users>
        <name>jill</name>
        <groups>123</groups>
        <groups>321</groups>
      </users>
      <users>
        <name>jack</name>
        <groups>123</groups>
        <groups>321</groups>
      </users>
      <users>
        <name>mary</name>
        <groups>123</groups>
        <groups>321</groups>
      </users>
    </settings>
  </test>
but that worked fine without throwing up my debug message that sub_cn had a non-null next pointer.
Can you think of a suitable test case?

2024-10-23 01:19 UTC, tony-vanderpeet commented on data.c
> +                        sub_cn = cn->children;
Never mind, I found a test case and yes, it did a whoopsy.

2024-10-24 01:01 UTC, gcampbell512 approved these changes

2024-10-24 01:14 UTC, closed without merging

2024-10-24 01:15 UTC, tony-vanderpeet commented
Superseded by a change in apteryx.